inherit_gem:
  govuk-lint: configs/rubocop/all.yml

AllCops:
  Include:
    - 'app/**/*.rb'
    - 'lib/**/*.rb'
    - 'lib/**/*.rake'
    - 'test/**/*.rb'
  
  Exclude:
    - 'bin/*'

Rails:
  Enabled: true