sudo: required
language: generic
services:
- docker
branches:
  only:
  - master
  - staging
  - prod
cache:
  directories:
  - "~/bundle-cache"
  - "~/npm-cache"
jobs:
  include:
  - stage: Build
    before_install:
    - mkdir -p ~/bundle-cache
    - mkdir -p ~/npm-cache
    install:
    - BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} ./ci/build-docker-images.sh
  - stage: Test
    name: Run Tests
    install: docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull
    before_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm start_dependencies
    script: docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web
      bin/rake db:create db:schema:load test
    after_script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml down
  - name: Static Analysis
    install:
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml pull
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml run --rm --no-deps web echo 'Gems pre-installed'
      - docker-compose -f docker-compose.yml -f docker-compose.ci.yml up -d web
    script:
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web bin/rubocop
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web bin/slim-lint
      app/views
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web yarn eslint
      app/assets/javascripts
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web yarn sass-lint
      -vq -c .sasslint.yml 'app/assets/stylesheets/**/*.scss'
    - docker-compose -f docker-compose.yml -f docker-compose.ci.yml exec web bin/brakeman
      --no-pager
  - stage: Deploy to int
    name: Deploy web
    if: branch = master AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=int COMPONENT=web ./ci/deploy-if-changed.sh
  - name: Deploy worker
    if: branch = master AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=int COMPONENT=worker ./ci/deploy-if-changed.sh
  - name: Deploy keycloak
    if: branch = master AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=int COMPONENT=keycloak ./ci/deploy-if-changed.sh
  - name: Deploy cosmetics
    if: branch = master AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=int COMPONENT=cosmetics-web ./ci/deploy-if-changed.sh
  - stage: Deploy to staging
    name: Deploy web
    if: branch = staging AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=staging COMPONENT=web ./ci/deploy-if-changed.sh
  - name: Deploy worker
    if: branch = staging AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=staging COMPONENT=worker ./ci/deploy-if-changed.sh
  - name: Deploy keycloak
    if: branch = staging AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=staging COMPONENT=keycloak ./ci/deploy-if-changed.sh
#  - name: Deploy cosmetics
#    if: branch = staging AND type != pull_request
#    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=staging COMPONENT=cosmetics-web ./ci/deploy-if-changed.sh
  - stage: Deploy to production
    name: Deploy web
    if: branch = prod AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=prod COMPONENT=web ./ci/deploy-if-changed.sh
  - name: Deploy worker
    if: branch = prod AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=prod COMPONENT=worker ./ci/deploy-if-changed.sh
  - name: Deploy keycloak
    if: branch = prod AND type != pull_request
    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=prod COMPONENT=keycloak ./ci/deploy-if-changed.sh
#  - name: Deploy cosmetics
#    if: branch = prod AND type != pull_request
#    script: BRANCH=${TRAVIS_BRANCH} BUILD_ID=${TRAVIS_BUILD_NUMBER} SPACE=prod COMPONENT=cosmetics-web ./ci/deploy-if-changed.sh
env:
  global:
  - secure: PP1MBuv5m3nsdgVS0UaX2CZPh1Ar8s6k+OZOaNn0oq4JSbvZXm/aEOX50D2AA9pxhXJBC+4NC54pWse9bRIt0etmmC+coYetjVI91xOgH2QgLbEkkfRKE/RKmtKqLAOyvVAB+HvVO/YNetIRGgTQwTnhvmsGL2uj/YFntTLRm/oHZy2vc7leN0gFSzS6oNK4a2L2+Tvl/Ytqhn2f2GUZnVTGJZoDYJKBRdlXZ/ffOsyaLXE8a1mgnuAx/7IUBkvtFKPcXOOtoe0mCU8O1AWszkfSv8GI5OtM54DLrM1b9bU8erkkCzDDSNBj+qDbvaTeGeDf2TH6fmtXSOBZhGpCkAOmaxzqt8RbpemnxM+ij40bXSPrOVGOspn6aPBli/vOxcCzchhl13aYSsRwf1AV+0uViX5Mve3sJnIvIEPH6bblzkRtGjLEWLyqGLU9Gb9l4Fxhxwx0kPmjkNqyhHjSBwTDd7FyDNKQ2k0DRU8hxUqUcKkHliQepN1Ri0manztiS/pf0JF2HDmovLEKC3Ag1EniR9sD74d1TH2lsm70t+Gk/8DGOh2Lbwy94pjUD/GDp0opdGRB5BynsW8TFCehnw/GlWQe7f/U2/X+jZ2oO7jw0eGlC1E9stGfcct8YnENrvrc1iHVQ9JJ78ZzIhnJ3GfD4A7ZKCmXIqucYlrgWSw= # DOCKER_USERNAME
  - secure: QF+c/OQR3qP+08J5dffdOFWypUIbYsHEeAZxl46AbR9iSaFxbCCltDAESdectTBN5I/RsVNezRfaZ1rtTCSo+F36qbpexwRkNQ/2B9+pnPr9pWkwvKvqlMAtotz8EkCjzG/DQvgMkaBxO8Q/bMv7/rCjv4Fvpmkb6k/MtyGgCcuhknK4kd2BhCEmJLcRr1Oin/SGgaZTRmlhhdZyzveO5Z5Y/8WyoMW6nXfGHOEv0JDcOQmURg2JN2vEhVKXkHlJ+Ij0ZDlL9ZCwuwCKcxe8BmgHMW1XidJwsHKPB/+q2AD8rHefKTU+CkKd55iNKZzD5p4Y8bqSJ1SbUQYaq6UaueqV1KKW7fXMmG8HLUP+rq28ZwnaMbTqdHlZeJHIkaKKS3ACgLOaCJN8lW13WTrHQBGgxE0PXpaSQCXhW9p7Dt0PEz4emsWarC3w0+Fx3t9yI5Zi6nTpEPIkGRgJQQXO6tW7wEzGlnPtQ0O+3kHb903DuwfKJPjmZ8MmTQsz7eP6qs07sKSMaCQ5eeDmAoKRcySM0iIMdgckGpDtYuZcgoGCuHxsGCOeVOjFsme+gPm7teHFRiH0pg0caNjLnTZer5UQBLGNLGSU4yTEgHjVmgZETEyh0fTAkBqiEfondGhCaoNUIrba5KFmC1tRDWyMsn8hr2H4Xyhmqi+OCqtc0L4= # DOCKER_PASSWORD
  - secure: j6Cgg+lhYfifEhp8XAF3pZQ2Xkco9Flxbp9TeniNVg26zK8OLGABfLrkU6olfi9sYF3Gq4JN/5oEJ8OYqp5CmNsuUnDhdsbDjsPVkg7h1oECirz8lCCPmM4CMmePclC03paZu8LiGA6yUY1n1VI7NItOeWdgi05mwxXjmW5ccwx4VldKLhcejGn0TtN8mZ13mryZpMXK6ifOs+Zy95yLbXQcXl3Z5o1vHd05XEnX3gMMmxCYcFSnYDq5k3xQmpNbRpPt/WHCm4os1lY+exdq+ZNfPMDXkwZgRBea2mU/BhHoNwwPd5ocQrU8yB1kkRy6z9fiPXMWipFdO9+uLl67Grm6hko9+sMeVr02Rzk8UyWfsW9iPI0/X3PRoYwgG7xQXOUwtcqSKowTMhC30rkf03Y2TBRSZsLc3emWyGvKz5alv2ZfjyAtiAEUwBUsmGr9t1DSHHt2bsQpz9NJvHh8uZU1Mzk3ZSn03m8i37UVAXWE6BOYJmDmkERpn+8bbqI/30gMk1c8sXW1gJyb6YyBeLxHt+hB4GAWvTqTbur5fkJUJKzZxqx0jGVtUmRpywT01n0yThH/6lHpFgaB6lgAPasn734WrLZF5SgTyF2z7DywfI7WYNPxfrWCEuOxXAyh4CwmMNhtULyL0JmG5+EhwqOLUVa8aS94Vtwyz37gAHM= # CF_USERNAME
  - secure: iZ+2Jcf4O2lvuOzzRMa+JU9feVfzZkKdUuH8pMT1zPnpn43f2CG8OIOC1JL4I4YuJnQZSdUKk3blI0Er163BjVDU5gZ3TyRdfH2UxxvQ7pB1O0G1ricBW/Qqv2JpG0Si8j5xOUI329bN69UU9QXgTltr+HYbXoUeLLqYr4ocpDDQb9/MjxsrbC0+cL60xDGse0mPIMeKTfcRehOaej/zsk+jdLaoFkBlC6DI+bQ6Cc/d+78TOtOZ9A98VJd3FjEAi3Fg2pohjTCTVek/7OlJKALYp9gTdRJY+prSeN9nHWEE35WOtEq86Id29ZoIPJ+alioJjxx9ZyNu+wDjhbj31u/WkLErkaN9I+x0+OuXmMDSRlNaTmePNtjA+4FwwAWkp0ZjD5h0BT1gdYntZGflgjIXwWvlq0cKovTwKwGUMcMLLOVpMcPW63kvSseqqMsPFI+G9d1BYcPBYwXmyLNyBWloUC5N8Up/9RCuGS9fUiqVmn8lT93HVla5YDYyjS3vcXIuR2za2gk8lXwEyMGZDcqafXsA+XN3borAuw3qfb5kHU5/zSijUswh4/2LD1ZICiQ5pohoy9pF3baWSF6psymqHXSrwWrHc00SOBpCqP7k4o06cywQrD1CW/aSohxTJpOFhjFOuJzgl7KDwbu/s/hCMSmB8Sdo1diXiEDJwsQ= # CF_PASSWORD
