version: '3'

services:
  web:
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0
    ports:
      - "1234:1234"
      - "3000:3000"
    environment:
      - NOTIFY_API_KEY=$NOTIFY_API_KEY
      - COMPANIES_HOUSE_API_KEY=$COMPANIES_HOUSE_API_KEY
      - GOVUK_REGISTERS_API_KEY=$GOVUK_REGISTERS_API_KEY
