version: '3'

services:
  db:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.2.3
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
  redis:
    image: redis
    hostname: redis
    volumes:
      - redis-volume:/data
  web:
    build: .
    volumes:
      - bundle-cache:/usr/local/bundle
      - npm-cache:/root/.npm
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}:/app
    depends_on:
      - db
      - elasticsearch
      - redis
  sidekiq:
    build: .
    command: bundle exec sidekiq
    volumes:
      - bundle-cache:/usr/local/bundle
      - npm-cache:/root/.npm
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}:/app
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  postgres-volume:
  elasticsearch-volume:
  redis-volume:
  bundle-cache:
  npm-cache:
