version: '3'

services:
  db:
    ports:
      - "5432:5432"

  elasticsearch:
    ports:
      - "9200:9200"

  keycloak:
    env_file:
      - .env
      - .env.keycloak
    volumes:
      - ${PWD-.}/keycloak/configuration:/opt/jboss/keycloak/configuration

  cosmetics-web:
    command: bin/rails s -p 3000 -b 0.0.0.0
    ports:
      - "3000:3000"
    env_file:
      - .env
      - .env.keycloak.cosmetics
  cosmetics-worker:
    env_file:
      - .env
      - .env.antivirus
