version: '3'

services:
  keycloak:
    environment:
      - NOTIFY_API_KEY=${NOTIFY_API_KEY}
    image: davidrendell/beis-mspsds-keycloak:${TRAVIS_BUILD_NUMBER}
  web:
    command: tail -f /dev/null
    image: davidrendell/beis-mspsds-web:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
      - ~/npm-cache:/root/.npm
    environment:
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
      - COMPANIES_HOUSE_API_KEY='not-a-key-but-fools-client-into-not-exploding'
  worker:
    command: tail -f /dev/null
    image: davidrendell/beis-mspsds-worker:${TRAVIS_BUILD_NUMBER}
    volumes:
      - ~/bundle-cache:/usr/local/bundle
  cosmetics-web:
    image: davidrendell/beis-mspsds-cosmetics-web:${TRAVIS_BUILD_NUMBER}
  db:
    image: davidrendell/beis-mspsds-db:${TRAVIS_BUILD_NUMBER}
  elasticsearch:
    image: davidrendell/beis-mspsds-elasticsearch:${TRAVIS_BUILD_NUMBER}
  start_dependencies:
    image: dadarek/wait-for-dependencies
    depends_on:
      - elasticsearch
      - keycloak
    command: elasticsearch:9200 keycloak:8080
