version: '3'

services:
  keycloak:
    environment:
      - NOTIFY_API_KEY=${NOTIFY_API_KEY}
  web:
    command: tail -f /dev/null
    volumes:
      - ~/bundle-cache:/usr/local/bundle
      - ~/npm-cache:/root/.npm
    environment:
      - CI
      - TRAVIS
      - TRAVIS_BRANCH
      - TRAVIS_JOB_ID
      - TRAVIS_PULL_REQUEST
  worker:
    command: tail -f /dev/null
    volumes:
      - ~/bundle-cache:/usr/local/bundle
