version: '3'

services:
  db:
    build:
      context: ./postgres
      dockerfile: Dockerfile
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  elasticsearch:
    build:
      context: .
      dockerfile: ./elasticsearch/Dockerfile
    environment:
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
  redis:
    image: redis
    hostname: redis
    volumes:
      - redis-volume:/data
  keycloak:
    build:
      context: ./keycloak
      dockerfile: Dockerfile
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_HOSTNAME=db
      - DB_DATABASE=keycloak
      - DB_USERNAME=keycloak
      - DB_PASSWORD=password
    depends_on:
    - db
    ports:
      - "8080:8080"
  web:
    build:
      context: .
      dockerfile: ./web/Dockerfile
    volumes:
      - bundle-cache:/usr/local/bundle
      - npm-cache:/root/.npm
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}:/app
    depends_on:
      - db
      - elasticsearch
      - redis
  worker:
    build:
      context: .
      dockerfile: ./worker/Dockerfile
    command: bin/sidekiq
    volumes:
      - bundle-cache:/usr/local/bundle
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}:/app
    depends_on:
      - db
      - elasticsearch
      - redis

volumes:
  postgres-volume:
  elasticsearch-volume:
  redis-volume:
  bundle-cache:
  npm-cache:
