version: '3'
services:
  db:
    image: postgres
    volumes:
      - postgres-volume:/var/lib/postgresql/data
  elasticsearch:
    image: elasticsearch
    environment:
      - "ES_JAVA_OPTS=-Xms750m -Xmx750m"
    volumes:
      - elasticsearch-volume:/usr/share/elasticsearch/data
  web:
    build: .
    command: bundle exec rdebug-ide --host 0.0.0.0 --port 1234 -- bin/rails s -p 3000 -b 0.0.0.0
    volumes:
      # ${PWD-.} calls PWD on systems which have that variable, and . on others e.g. windows
      - ${PWD-.}:/app
    ports:
      - "1234:1234"
      - "3000:3000"
    environment:
      - NOTIFY_API_KEY=$NOTIFY_API_KEY
    depends_on:
      - db
      - elasticsearch
volumes:
  postgres-volume:
  elasticsearch-volume:
