version: '3'

services:
  web:
    command: tail -f /dev/null
    volumes:
      - ~/bundle-cache:/usr/local/bundle
      - ~/npm-cache:/root/.npm
  worker:
    command: tail -f /dev/null
    volumes:
      - ~/bundle-cache:/usr/local/bundle
