default: &default
  adapter: postgresql
  encoding: unicode
  host: db
  username: postgres
  password:
  pool: 5

development:
  <<: *default
  database: mspsds_development

test:
  <<: *default
  database: mspsds_test

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("mspsds-database")["uri"] %>
  connect_timeout: 2
  variables:
    statement_timeout: 500
