default: &default
  host: 'redis'
  db: 0

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("mspsds-redis-queue")["uri"] %>
