source "https://rubygems.org"

ruby File.read(".ruby-version").strip

gem "axlsx", git: "https://github.com/randym/axlsx.git", ref: "c593a08"
gem "axlsx_rails"
gem "cf-app-utils"
gem "jbuilder", "~> 2.9"
gem "pg", "~> 1.1"
gem "pghero"
gem "puma", "~> 3.12"
gem "pundit"
gem "redcarpet"
gem 'redis-rails'
gem "rubyzip", ">= 1.2.1"
gem "slim-rails"
gem "strong_migrations"
gem "wicked"
gem "govuk_publishing_components"
# Use SCSS for stylesheets
gem 'sass-rails', '~> 5.0'

# Use Uglifier as compressor for JavaScript assets
gem 'uglifier', '>= 2.7.2'

# Use jquery as the JavaScript library
gem 'jquery-rails'

gem "shared-web", path: "./vendor/shared-web"


group :development, :test do
  gem "roo", "~> 2.8.2"
  gem "rspec-mocks"

  gem "shared-web-dev", path: "./vendor/shared-web/dev"
end
