---
product_category:
  - Alarms
  - Baby/children's products
  - Clothing (including baby clothes)
  - Cosmetics
  - Fancy dress
  - Furniture and furnishings
  - Lasers
  - Low voltage equipment (including plugs and sockets)
  - Measuring instruments (including pressure)
  - Personal protective equipment (PPE)
  - Pyrotechnics
  - Sanitary products
  - Small electronics
  - Toys
  - White goods
  - Other product type
