default: &default
  host: 'redis'
  db: 1

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("psd-session")["uri"] %>
