default: &default
  :host: 'elasticsearch'
  :transport_options:
    :request:
      :timeout: 5

development:
  <<: *default

test:
  <<: *default

production:
  :url: <%= ENV["VCAP_SERVICES"] && CF::App::Credentials.find_by_service_name("mspsds-elasticsearch")["uri"] %>
