
default: &default
  :host: 'elasticsearch'
  :transport_options:
    :request:
      :timeout: 5

development:
  <<: *default

test:
  <<: *default

production:
  :url: <%= ENV['VCAP_SERVICES'] && JSON.parse(ENV['VCAP_SERVICES'])["elasticsearch"][0]["credentials"]["uri"] %>
