
default: &default
  host: 'redis'

development:
  <<: *default

test:
  <<: *default

production:
  url: <%= ENV['VCAP_SERVICES'] && JSON.parse(ENV['VCAP_SERVICES'])["redis"][0]["credentials"]["uri"] %>
